[package]
name = "testanns"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
byteorder = "1.5"
clap = { version = "4.5.6", features = ["derive"] }
rand = "0.8"
plotters = "0.3"
indicatif = "0.17"